### ISSUE TITLE
getting errors on frontend when starting microservices version of this site

### ISSUE THREAD

**Issue by mconstant** [jarrodmalkovic/auction-website-monolith#18]
when I try to hit the ingress url (auctionweb.site) frontend throws this error : https://pastebin.com/vnZB51Ez

```
[frontend] event - build page: /next/dist/pages/_error
[frontend] wait  - compiling...
[frontend] error - ./src/pages/_app.tsx
[frontend] MacroError: /app/src/pages/_app.tsx: TypeError: xwind/macro - Cannot read property 'theme' of undefined
[frontend] Error: Cannot find module '/app/.next/server/pages-manifest.json'
[frontend] Require stack:
[frontend] - /app/node_modules/next/dist/next-server/server/require.js
[frontend] - /app/node_modules/next/dist/next-server/server/load-components.js
[frontend] - /app/node_modules/next/dist/next-server/server/api-utils.js
[frontend] - /app/node_modules/next/dist/next-server/server/next-server.js
[frontend] - /app/node_modules/next/dist/server/next.js
[frontend] - /app/node_modules/next/dist/server/lib/start-server.js
[frontend] - /app/node_modules/next/dist/cli/next-dev.js
[frontend] - /app/node_modules/next/dist/bin/next
[frontend]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
[frontend]     at Function.mod._resolveFilename (/app/node_modules/next/dist/build/webpack/require-hook.js:4:1784)
[frontend]     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
[frontend]     at Module.require (internal/modules/cjs/loader.js:952:19)
[frontend]     at require (internal/modules/cjs/helpers.js:88:18)
[frontend]     at getPagePath (/app/node_modules/next/dist/next-server/server/require.js:1:657)
[frontend]     at requirePage (/app/node_modules/next/dist/next-server/server/require.js:1:1062)
[frontend]     at loadComponents (/app/node_modules/next/dist/next-server/server/load-components.js:1:795)
[frontend]     at DevServer.findPageComponents (/app/node_modules/next/dist/next-server/server/next-server.js:77:296)
[frontend]     at DevServer.renderErrorToHTML (/app/node_modules/next/dist/next-server/server/next-server.js:139:209)
[frontend]     at DevServer.renderErrorToHTML (/app/node_modules/next/dist/server/next-dev-server.js:35:1147)
[frontend]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[frontend]     at async DevServer.render (/app/node_modules/next/dist/next-server/server/next-server.js:75:236)
[frontend]     at async Object.fn (/app/node_modules/next/dist/next-server/server/next-server.js:59:580)
[frontend]     at async Router.execute (/app/node_modules/next/dist/next-server/server/router.js:25:67)
[frontend]     at async DevServer.run (/app/node_modules/next/dist/next-server/server/next-server.js:69:1042) {
[frontend]   code: 'MODULE_NOT_FOUND',
[frontend]   requireStack: [
[frontend]     '/app/node_modules/next/dist/next-server/server/require.js',
[frontend]     '/app/node_modules/next/dist/next-server/server/load-components.js',
[frontend]     '/app/node_modules/next/dist/next-server/server/api-utils.js',
[frontend]     '/app/node_modules/next/dist/next-server/server/next-server.js',
[frontend]     '/app/node_modules/next/dist/server/next.js',
[frontend]     '/app/node_modules/next/dist/server/lib/start-server.js',
[frontend]     '/app/node_modules/next/dist/cli/next-dev.js',
[frontend]     '/app/node_modules/next/dist/bin/next'
[frontend]   ]
[frontend] }
[frontend] Error: Cannot find module '/app/.next/server/pages-manifest.json'
[frontend] Require stack:
[frontend] - /app/node_modules/next/dist/next-server/server/require.js
[frontend] - /app/node_modules/next/dist/next-server/server/load-components.js
[frontend] - /app/node_modules/next/dist/next-server/server/api-utils.js
[frontend] - /app/node_modules/next/dist/next-server/server/next-server.js
[frontend] - /app/node_modules/next/dist/server/next.js
[frontend] - /app/node_modules/next/dist/server/lib/start-server.js
[frontend] - /app/node_modules/next/dist/cli/next-dev.js
[frontend] - /app/node_modules/next/dist/bin/next
[frontend]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
[frontend]     at Function.mod._resolveFilename (/app/node_modules/next/dist/build/webpack/require-hook.js:4:1784)
[frontend]     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
[frontend]     at Module.require (internal/modules/cjs/loader.js:952:19)
[frontend]     at require (internal/modules/cjs/helpers.js:88:18)
[frontend]     at getPagePath (/app/node_modules/next/dist/next-server/server/require.js:1:657)
[frontend]     at requirePage (/app/node_modules/next/dist/next-server/server/require.js:1:1062)
[frontend]     at loadComponents (/app/node_modules/next/dist/next-server/server/load-components.js:1:795)
[frontend]     at DevServer.findPageComponents (/app/node_modules/next/dist/next-server/server/next-server.js:77:296)
[frontend]     at DevServer.renderErrorToHTML (/app/node_modules/next/dist/next-server/server/next-server.js:139:209)
[frontend]     at DevServer.renderErrorToHTML (/app/node_modules/next/dist/server/next-dev-server.js:35:1147)
[frontend]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[frontend]     at async DevServer.render (/app/node_modules/next/dist/next-server/server/next-server.js:75:236)
[frontend]     at async Object.fn (/app/node_modules/next/dist/next-server/server/next-server.js:59:580)
[frontend]     at async Router.execute (/app/node_modules/next/dist/next-server/server/router.js:25:67)
[frontend]     at async DevServer.run (/app/node_modules/next/dist/next-server/server/next-server.js:69:1042) {
[frontend]   code: 'MODULE_NOT_FOUND',
[frontend]   requireStack: [
[frontend]     '/app/node_modules/next/dist/next-server/server/require.js',
[frontend]     '/app/node_modules/next/dist/next-server/server/load-components.js',
[frontend]     '/app/node_modules/next/dist/next-server/server/api-utils.js',
[frontend]     '/app/node_modules/next/dist/next-server/server/next-server.js',
[frontend]     '/app/node_modules/next/dist/server/next.js',
[frontend]     '/app/node_modules/next/dist/server/lib/start-server.js',
[frontend]     '/app/node_modules/next/dist/cli/next-dev.js',
[frontend]     '/app/node_modules/next/dist/bin/next'
[frontend]   ]
[frontend] }
[frontend] error - ./src/pages/_app.tsx
[frontend] MacroError: /app/src/pages/_app.tsx: TypeError: xwind/macro - Cannot read property 'theme' of undefined
```

**Comment by tigwyk** [comment]
Additionally trying different versions of some of the supporting NPM modules in frontend's package.json didn't make a difference.
